8.2XS82ECU1041
xcp-ng-rpms/xen pull request #27
Opened 2023-07-24 19:17 UTC by gduperrey

2023-07-25 07:58 UTC, benjamreis requested changes

2023-07-25 07:58 UTC, benjamreis commented on SPECS/xen.spec
> +==== BASE ====
Merge line to be removed.

2023-07-25 08:04 UTC, andSmv approved these changes

2023-07-25 08:07 UTC, Wescoeur approved these changes
Approved after the change indicated by Benjamin.

2023-07-25 08:20 UTC, benjamreis approved these changes

2023-07-25 09:47 UTC, merged

2023-08-18 10:55 UTC, stormi commented on SPECS/xen.spec
> +- Update to Xen 4.13.5
All our previous changelog history was lost in this PR.